replaceDict = {
	"Jan": "January",
	"Feb": "February",
	"Mar": "March",
	"Apr": "April",
	"Jun": "June",
	"Jul": "July",
	"Aug": "August",
	"Sept": "September",
	"Oct": "October",
	"Nov": "November",
	"Dec": "December",
	# "im": "i am",
	# "i'll": "i will",
	# "i've": "i have",
	# "you're": "you are",
	# "you'll": "you will",
	# "you've": "you have",
	# "he'll": "he will",
	# "shes": "she is",
	# "she'll": "she will",
	# "it'll": "it will",
	# "we're": "we are",
	# "we'll": "we will",
	# "we've": "we have",
	# "they're": "they are",
	# "they'll": "they will",
	# "they've": "they have",
	# "this'll": "this will",
	# "that'll": "that will",
	# "theres": "there is",
	# "there's": "there is",
	# "there'll": "there will",
	# "isn't": "is not",
	# "wasn't": "was not",
	# "aren't": "are not",
	# "weren't": "were not",
	# "hasn't": "has not",
	# "haven't": "have not",
	# "hadn't": "had not",
	# "don't": "do not",
	# "doesn't": "does not",
	# "didn't": "did not",
	# "won't": "will not",
	# "wouldn't": "would not",
	# "cant": "can not",
	# "can't": "can not",
	# "couldn't": "could not",
	# "shouldn't": "should not",
	"U": "you",
	"btwn": "between",
	"Nooooooooo": "No",
	"y'all": "you all",
	"tho": "though",
	"ep": "episode",
	"mins": "minutes",
	"Okay": "OK",
	"haha": "hah",
	"hahahaha": "hah",
	"let's": "let us",
	"yr": "year",
	"agn": "again",
	"would've": "would have",
	
	"diff": "difficult",
	"i c": "i see",
	"Thanx": "thanks",
	"b": "been",
	"looooooonnnngggggggg": "long",
}

# indeterminacy = {
# 	"perf": 43,
# 	"'s": 59,
# 	"ur goin": 60,
# 	"s mo...": 72,
# 	"gon": 92,
# 	"lol": 94,
# 	#143,
# 	"re elected":202
# }

# stop = {
# 	"hmmmm",
# 	"hah",
# 	"Uh",
# 	"Yay",

# }
